[package]
name = "render_sbgn_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cairo-rs = { version = "0.18.5", features = ["png", "svg"] }
clap = { version = "4.5", features = ["derive"] }
pango = "0.18.3"
pangocairo = "0.18.0"
roxmltree = "0.19.0"
